### ISSUE TITLE
Schedule L (ver 8.1) data description ambiguous

### ISSUE THREAD

**Issue by roberthadow** [18F/FEC#3931]
Data lines with FORM_TYPE = SL (ver 8.1) are described at http://www.fec.gov/elecfil/eFilingFormats.zip which describes the same data multiple times. For example:
**4(a). Voter Registration DISBURSEMENTS** is described as the eighth and twenty-fifth elements
**4(e) Line 4 Total** is described as the seventeenth and thirty-fourth elements.

I'm willing to bet this riddle could be solved if there was an old paper form available to use as a sample.  It seems likely that this is the result of a cut-n-paste exercise.

**Comment by jwchumley** [comment]
This is probably correct. I'll send to the efiling office and have them check and update.

**Comment by jwchumley** [comment]
Oh. Actually I think this is just confusion we've run into before because the spreadsheet is separated into Column A and Column B sections and that isn't necessarily clear when you look at it. The format documentation will be reviewed along with everything else when we start the efiling upgrade project.

**Comment by roberthadow** [comment]
OK, I got it. The same problem exists elsewhere, but now that I conquered it and no one else seems to care, let's close the ticket. Thanks
