### ISSUE TITLE
Completeness of data sets

### ISSUE THREAD

**Issue by roberthadow** [18F/FEC#3948]
My boss asked me if we were downloading all of the FEC data.  I told him we were certainly getting each daily ZIP, each containing FEC files with more or less serial numbering.  A check showed that about 83% of the possible file names are being used.  
How might one assure herself that all of the available data is included in the daily ZIPs?  A record total, a check digit, something?

**Comment by jwchumley** [comment]
We don't have a check for the files that go into the nightly zips. The missing report ids are due to the fact that the sequence that generates them also generates the report ids for paper filings which don't go into the nightly zip files.

You could use the the API at https://api.open.fec.gov/developers/ to create your own list of report ids.

**Comment by roberthadow** [comment]
Many thanks, Chumley
