### ISSUE TITLE
Revise bulleted list https://beta.fec.gov/legal-resources/advisory-opinions-process/

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/FEC#4037]
In the following bulleted list, do we want to use periods or commas?

Advisory opinions can answer questions about:

The Federal Election Campaign Act, which is codified in Title 52 of the U.S. Code, Sections 30101-30146

The laws about public financing of presidential campaigns and conventions, which are codified in Title 26 of the U.S. Code, Chapters 95 and 96.

The Commission’s regulations, which are codified at Title 11 of the Code of Federal Regulations.

<3 jme

**Comment by jamiealbrecht** [comment]
Same for this one. I think there should be commas not periods. 

A request does not qualify as a complete advisory opinion request if it:

Asks a general question of interpretation.
Asks about a hypothetical situation.
Asks about the activities of someone other than the requestor.
Asks about past activities that the requestor does not plan to continue in the future.
Does not contain all of the factual information relevant to the activity that is the subject of the request.

**Comment by jamiealbrecht** [comment]
Also on this page, the first sentence looks like it might have an extra space in it. <333

**Comment by emileighoutlaw** [comment]
Such a good note! Just thinking through this as I type: usually when each bullet completes the sentence before the colon, we can use periods. For example— 

At the lake you can:
- Go for a swim.
- Lounge on the beach.
- Get sunburned.


But it is also equally accepted to do it like this:

At the lake you can:
- Go for a swim
- Lounge on the beach
- Get sunburned


Since this case we want to be clear that each of these things is distinct
> A request does not qualify as a complete advisory opinion request if it asks a general question of interpretation.
> A request does not qualify as a complete advisory opinion request if it asks about a hypothetical situation.
> A request does not qualify as a complete advisory opinion request if it asks about the activities of someone other than the requestor.

I think periods makes the most sense. :) 💟
