### ISSUE TITLE
Slight Blurring of Form Images

### ISSUE THREAD

**Issue by jjonesfec** [18F/FEC#4602]
The form images appear to be slightly blurry when viewed in the browser but are crisp and clear when copied to the desktop. While not crippling in this instance, this blurring is concerning as it could compromise the readability of images with small type.

I've uploaded an screen cap from my desktop that shows the difference between the web version and the desktop version. On the left, you see the image as it appears in the browser. On the right, you see that same image after it was selected and copied to the desktop. The blur appears regardless of browser, so the cause is probably elsewhere.

![screen shot 2017-10-19 at 10 01 19 am](https://user-images.githubusercontent.com/10223901/31775350-5b27926e-b4b6-11e7-80c7-d65502decd7b.png)

**Comment by jjones0618** [comment]
The website looks to be enlarging the image just enough to potentially be the culprit. The images are built to a 560px standard width. Is the template expecting larger files?

**Comment by jenniferthibault** [comment]
Thanks so much for filing this @jjones0618 that's definitely problematic. We are prepping a really complicated release right now, and just started a new sprint, so likely can't assign someone to take a look at it yet. I'll apply the `Bug` label and bring it up in next week's grooming session as a front end task.

Thanks!

**Comment by jjones0618** [comment]
Uploading images at 2x resolution resolved the blurring issue but without knowing why. Clearly something in the code was affecting their appearance. Downsampling for mobile?!?

**Comment by jenniferthibault** [comment]
Awesome! Glad we have a solution we could use. 

I'd like to diagnose the problem so that we can understand what's happening to images under the hood, and if it's something we can control or something that's baked in to wagtail. 

Since reporting example images contain so much text, it might make sense to go ahead and replace them with 2x images for now, and use that as a future export setting. I think I'd wait on doing a site-wide image replacement until we diagnose the cause.
