### ISSUE TITLE
User feedback: AO legal citations missing

### ISSUE THREAD

**Issue by JonellaCulmer** [18F/FEC#4613]
Received feedback regarding [AO 2016-24](https://www.fec.gov/data/legal/advisory-opinions/2016-24/) from user via email: 

> I was just looking at the above referenced AO and noticed that in the Legal Citations box, it says that the AO does not cite statutes and regulations.  It does.  It picked up the other AOs cited, but not the statutes and regulations.

**Comment by AmyKort** [comment]
@vrajmohan  Is this related to the way citations appear in our documents--the spacing, the section symbols, etc.? I feel like we've run into this before.

**Comment by vrajmohan** [comment]
It is indeed due to the _inconsistent_ way the citations appear in the documents. In this case, it is due to "C.F.R." instead of "CFR" in "11 C.F.R. § 100.15", and the § symbol is followed by an unexpected space in "52 U.S.C. § 30101". These 2 cases are relatively easy fixes. My estimate is 1 to fix them. We would have to then reload the AOs and back them up again, which would make it a 2.
