### ISSUE TITLE
OpenFEC Readme.md updates needed

### ISSUE THREAD

**Issue by cptechiegal** [18F/FEC#4753]
The following items need updating at the OpenFEC Readme.md
 1) Update the section on: Set other environment variables
Correction to env var:FEC_WEB_API_URL - should be: FEC_API_URL
2) Update the section on: Create local databases
a)To include warning added about: ./manage.py update_all
i.e., never to 'update all' when pointing to an rds box via the SQLA_CONN env var
b) Include additional information to the subsection about the use of SQLA_CONN env var for connection to non-local DB using RDS

**Comment by cptechiegal** [comment]
Will make a PR for this instead.

**Comment by jenniferthibault** [comment]
@cptechiegal it's good practice to have an issue for every PR so that you can point to what's needed in more detail in an issue. That also allows us to assign the issue to someone, keep the work visible on our project board, and prioritize it among other work.

I'll re-open this, assign it to you, and when your PR that addresses it is merged in, we can close it again 🎉 .

**Comment by cptechiegal** [comment]
This work was completed on 12/04/17 as PR#2787
