### ISSUE TITLE
Number of Donors info

### ISSUE THREAD

**Issue by gouldc2** [18F/FEC#48]
The FEC does a great job of breaking donation info up by candidate and by donation amount, but it is very hard to find how many unique contributors donated to each candidate, and how many people gave small vs large donations. Since only dollar amounts are shown it is not transparent to see if the >$2000 category came from a few or a lot of people. Currently the only way to find out this information is to download the raw data spreadsheet, and then manipulate to take out multiple donations by the same person to find the number of unique donors. I think this is a much better gauge of a candidates popularity and "grassroots movement" claim then the amount of money raised which is widely publicized. Please add this info so I don't have to hunt for it.

**Comment by gouldc2** [comment]
![image](https://cloud.githubusercontent.com/assets/13370745/8733712/1fe39284-2bba-11e5-8ab9-20da397f7753.png)

Sample for new info

**Comment by LindsayYoung** [comment]
The information comes from the forms that committees file. The committees are not required to itemize contributions $200 and under, so we will never know the exact number of those donations. You can look for the number of itemized donations, but that will underrepresent the number of donations from campaigns that take in many small donations.

**Comment by gouldc2** [comment]
Not required, but guessing candidates do have that information (so they can call upon those people to donate again) and some chose to report it. How would it be reported otherwise? As a transfer?

Could you report the data for the other amounts?

**Comment by LindsayYoung** [comment]
Some committees do itemize small amounts in the schedule A section of the form, where itemized  contributions are reported. Otherwise, the total amount of unitemized donations are reported on the summary part of the form.

**Comment by gouldc2** [comment]
So does breakdown of contribution data get reported directly from the
candidate or is it verified by someone in the FEC?

[image: Inline image 1]

**Comment by LindsayYoung** [comment]
All of the information is from form reported by the candidate. You are looking at the presidential map so that comes from [form 3p](http://www.fec.gov/pdf/forms/fecfrm3p.pdf). 

I know the data, but I don't know about compliance or enforcement. If you have questions along those lines, you will have to contact the FEC.

**Comment by LindsayYoung** [comment]
I realized I missed one of your questions.

Campaigns to keep track of donors because they need to make sure they don't take contributions that exceed campaign contribution limits. You can see committee's year to date numbers for the contributions, but be careful with those, since they can be refunded in a way that is not reflected in previous totals.

It also can get tricky since names are not good identifiers. James Harper could be the same or different person from James P. Harper, similarly, addresses and other information can be reported slightly differently in a way that makes it hard to figure out if people are the same.

**Comment by LindsayYoung** [comment]
I am going to close this. Thanks for writing and feel free to post and additional questions as new issues.
