### ISSUE TITLE
Gathering feedback on time period selection tool

### ISSUE THREAD

**Issue by jenniferthibault** [18F/FEC#73]
We're exploring several options that will allow users to personalize timespans on candidate pages. 

Below are four options, using a Senate election as an example. We eventually plan to apply these concepts to presidential and House candidates, too. 

Please leave your thoughts on each option in the comment fields below. Your feedback will help us improve our designs.

### Option A: single drop down
The user can select either:
- Two-year periods within each election cycle, or
- The full cycle for each election the candidate  ran in.

![candidate - senate copy](https://cloud.githubusercontent.com/assets/11636908/10526094/bfacaa92-7356-11e5-984a-882a0bb04157.png)

### Option B: two steps— drop down and toggle

1. The drop down shows every election the candidate ran in. 
2. The toggle button breaks down the selected election into two-year periods or the full cycle.

![candidate - senate copy 2](https://cloud.githubusercontent.com/assets/11636908/10526105/cbe963a4-7356-11e5-85a2-474a9cf22800.png)

### Option C: two drop downs

1. The first drop down shows every election the candidate ran in
2. The second drop down breaks the selected election into two-year periods or the full cycle.

![candidate - senate copy 3](https://cloud.githubusercontent.com/assets/11636908/10526106/cbee51b6-7356-11e5-879c-51e032d56b84.png)

### Option D: two steps— drop down and slider

1. The drop down shows every election the candidate ran in. 
2. The slider allows users to select any amount of time from the selected election, broken down by quarters.

![candidate - senate copy 4](https://cloud.githubusercontent.com/assets/11636908/10526108/cc01e078-7356-11e5-99f3-445c74b93966.png)

**Comment by IanLee1521** [comment]
So for the "two step" options, are these "either / or" ? E.g. (with option D for instance) I would select an Election or a time period? It's not clear to me exactly how these two options would relate. Alternatively, I suppose selecting a Election from the dropdown would select a Time Period for that election in the slide?

**Comment by jenniferthibault** [comment]
Great clarification, thank you @IanLee1521! These two-step options would be "and" situations. 

First, select the election cycle, (for this senate example, it is a six year period, but presidential would be 4, etc) AND THEN select the time period within that cycle you'd like to look at specifically.

It can be the "full cycle" of six years, which would be the default second option if the user didn't change it, or any two year period within that. Option D would be the exception, which uses sliders to break the cycle down into quarters, and is not locked to two year time frames.

We are trying to find a design solution that makes it easier for users to see totals if they want to, instead of having to add up individual two-year cycles that the data is packaged in now.

**Comment by tlyles** [comment]
Options A and C are easier on the eye. I understand why the slider or toggle (options B and D) type be sexier, but, as a user, I just need to see the all the dates. Having drop-down menus is just easier on the eye.

**Comment by kdodia** [comment]
It took me a few seconds to find that dropdown in the first place, as it is tucked away in the corner in the current beta version; I did not notice it because it is visually embedded in a block of otherwise static content:

![americans_for_prosperity_-_committee_overview_-_beta_fec_gov](https://cloud.githubusercontent.com/assets/4944634/10822957/4bf61da0-7e27-11e5-957d-b6fda45ff82f.png)

I am in strong favor of Option **D**. Selecting by campaign cycle from the dropdown is a quick one-step for most users, but the flexibility of a slider is valuable for deeper perusal of time trends, especially if (or when!) visualizations might hit this page. Plus as this campaign cycle heats up, I imagine inspection by quarter will be a common operation.

Past that, I would prefer **B** over **C**, as it displays the year-block options inline and saves a click to activate the second dropdown.

And to be clear, **A** is a perfectly fine option, although I would appreciate a more visually prominent toggle located closer to the table.

*Thank you for caring deeply about the user experience!!*

**Comment by onezerojeremy** [comment]
After discussions and the usability results, (plus the need to start developing something to test) I think we should try option B. 

Reasons:
1. The underlying aggregate data only consistently allows comparison between filings. Because filings schedules do not all line up (quarterly, monthly, special filings) and novice users may not understand the shape of the data, giving more control than option B may give users the sense that they can compare things which are in not comparable, or require a somewhat more complex user interface to compare. (@LindsayYoung, please correct me if I got this wrong.)
2. We are not yet getting strong signals from either the feedback tool or usability sessions that more granular date parsing will be immensely more useful, and,
3. the more granular date parsing will require more development time and, once developed, may incur a marginal performance cost (this performance cost will likely fall under the user perception threshold during normal use periods)
4. It solidly outperforms option A in usability testing. Option C, in having multiple drop downs, seems more elaborate and confusing and requires an extra click. War on clicks! 


There are still some user interface issues that need to be ironed out:
1. People want Option B toggles in chronological order, after the full election cycle toggle. 
2. The full cycle toggle may need to be visually tweaked to show you're selecting everything after it. @noahmanger can provide a bit more context here.
3. The links to the election pages now compete with the election drop down. We need to tweak this: possibly by only including a link to the drop-down selected election (as perhaps a more substantial call to action), not sure. 
4. The election pages will likely use the same option B control, but may need another iteration in terms of how they showcase multiple candidates and the years of their elections.

**Comment by jenniferthibault** [comment]
The first iteration of this, which most closely resembles option B, has just been implemented on the site. Closing this issue, but feedback is still welcome in the form of new issues, or using the website's feedback tool, which will file an issue on your behalf from anywhere on beta.fec.gov. Thanks everyone!
